In [213]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, mean_squared_error, accuracy_score

In [214]:
df=pd.read_csv('/Users/varsha/Desktop/orig2.csv')
df.head()


ID  Tinea captisis  Alopecia areata  Melanoma  Healthy scalp     Img  \
0   1               1                0         0              0  1.jpeg   
1   2               1                0         0              0  2.jpeg   
2   3               1                0         0              0  3.jpeg   
3   4               1                0         0              0  4.jpeg   
4   5               1                0         0              0  5.jpeg   

                                                 pic  \
0  [[[ 60  67  75]\n  [ 60  66  75]\n  [ 58  65  ...   
1  [[[ 92  81  77]\n  [ 84  73  69]\n  [ 66  55  ...   
2  [[[  6  58  98]\n  [  6  58  98]\n  [ 17  69 1...   
3  [[[ 4  0  0]\n  [ 5  1  0]\n  [ 7  3  0]\n  .....   
4  [[[ 12   4   1]\n  [ 12   4   1]\n  [ 13   5  ...   

                                       segmented_img  \
0  [[[0 0 0]\n  [0 0 0]\n  [0 0 0]\n  ...\n  [0 0...   
1  [[[0 0 2]\n  [0 0 2]\n  [0 0 2]\n  ...\n  [0 0...   
2  [[[1 0 0]\n  [1 0 0]\n  [1 0 0]\n  ...\n  [0 0...   
3  [[[0 0 0]\n  [0 0 0]\n  [0 0 0]\n  ...\n  [0 0...   
4  [[[0 0 0]\n  [0 0 0]\n  [0 0 0]\n  ...\n  [0 0...   

                                              colour  num_contours  ...  \
0  (48.514639668367344, 45.396026785714284, 44.45...             3  ...   
1  (51.35983099489796, 42.72837691326531, 35.8404...             6  ...   
2  (36.319072066326534, 28.56017538265306, 30.999...            10  ...   
3  (112.42542091836735, 88.4951243622449, 69.3985...            10  ...   
4  (47.09440051020408, 35.94358737244898, 32.7537...             6  ...   

   height_width_ratio  central_width  central_height  smaller_half_dist  \
0            1.515284            229             347              114.5   
1            1.235437            412             509              206.0   
2            0.902128            470             424              212.0   
3            1.153318            437             504              218.5   
4            0.844920            374             316              158.0   

     circle_area  circle_area_ratio  colour1  zeroes   \
0   41187.065087           0.417122    peach    50388   
1  133316.625848           0.795365   yellow    50310   
2  141195.740223           0.633102   yellow    50566   
3  149986.701866           0.755776    peach    50310   
4   78426.719004           0.527455   yellow    50414   

                                               skel  lines  
0  [[  0   0   0 ...   0   0   0]\n [  0   0   0 ...    60  
1  [[  0   0   0 ...   0   0   0]\n [  0   0   0 ...     5  
2  [[  0   0   0 ...   0   0   0]\n [  0   0   0 ...   234  
3  [[0 0 0 ... 0 0 0]\n [0 0 0 ... 0 0 0]\n [0 0 ...   176  
4  [[0 0 0 ... 0 0 0]\n [0 0 0 ... 0 0 0]\n [0 0 ...     2  

[5 rows x 23 columns]

In [215]:
list(df.columns)

['ID',
 'Tinea captisis',
 'Alopecia areata',
 'Melanoma',
 'Healthy scalp',
 'Img',
 'pic',
 'segmented_img',
 'colour',
 'num_contours',
 'area_contours',
 'len_contours',
 'area',
 'height_width_ratio',
 'central_width',
 'central_height',
 'smaller_half_dist',
 'circle_area',
 'circle_area_ratio',
 'colour1',
 'zeroes ',
 'skel ',
 'lines']

In [216]:
df['colour1'] = df['colour1'].map( {'yellow':1, 'pink':2, 'white':3,'peach':4,'red':5,'black':6} )

In [217]:
X=df[['area','central_height','central_width','height_width_ratio','smaller_half_dist',
 'circle_area','circle_area_ratio','num_contours','area_contours','len_contours','zeroes ','colour1']]

In [218]:
y = df['Healthy scalp'].to_numpy()

In [219]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, shuffle=True)

In [220]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
'''df['area']=sc.transform(df['area'])
df['height']=sc.transform(df['height'])
df['width']=sc.transform(df['width'])
df['height_width_ratio']=sc.transform(df['height_width_ratio'])'''

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [221]:

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs')
classifier.fit(X_train, y_train)


LogisticRegression()

In [222]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print('Accuracy for healthy scalp: '+str(accuracy_score(y_test, y_pred))) 
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy for healthy scalp: 0.9117647058823529
[[58  0]
 [ 6  4]]
              precision    recall  f1-score   support

           0       0.91      1.00      0.95        58
           1       1.00      0.40      0.57        10

    accuracy                           0.91        68
   macro avg       0.95      0.70      0.76        68
weighted avg       0.92      0.91      0.90        68



In [223]:
#SVM
from sklearn.svm import SVC 
svmclf = SVC() 
svmclf.fit(X_train, y_train) 
  
# Storing the predictions of the non-linear model 
y_pred = svmclf.predict(X_test) 
  

from sklearn.metrics import r2_score
# Evaluating the performance of the non-linear model 
print('Accuracy for Melanoma : ' +str(accuracy_score(y_test, y_pred))) 
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy for Melanoma : 0.8529411764705882
[[58  0]
 [10  0]]
              precision    recall  f1-score   support

           0       0.85      1.00      0.92        58
           1       0.00      0.00      0.00        10

    accuracy                           0.85        68
   macro avg       0.43      0.50      0.46        68
weighted avg       0.73      0.85      0.79        68



/Users/varsha/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/varsha/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/varsha/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [224]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
y_pred=neigh.predict(X_test)
print('Accuracy for Healthy scalp: ' +str(accuracy_score(y_test, y_pred))) 
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy for Healthy scalp: 0.8529411764705882
[[55  3]
 [ 7  3]]
              precision    recall  f1-score   support

           0       0.89      0.95      0.92        58
           1       0.50      0.30      0.37        10

    accuracy                           0.85        68
   macro avg       0.69      0.62      0.65        68
weighted avg       0.83      0.85      0.84        68



In [64]:
#Colour

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import cv2
from skimage.color import rgb2gray
from skimage.io import imread, imshow
from scipy import ndimage
from PIL import Image,ImageChops
#from colours import color_analysis1
import math 
import os
import glob 
import random


from collections import Counter
import webcolors
import cv2
from PIL import Image 

df=pd.read_csv('/Users/varsha/Desktop/Capstone project/resp2.csv')
print(df.head())
list(df.columns)
df.shape

# COLOURS = {   "red": (255, 0, 0),
#               "green" : (0,255,0),
#               "blue":(0,0,255),
#               "pink":(255,192,203),
#               "white":(255,250,250),
#               "yellow":(255,255,0),
#               "purple":(221,160,221)
#               }

COLOURS = { "yellow": (51, 42, 31),
           "white":(65,50,90), 
           "peach":(50,65,146), 
           "black": (80,90,100)
          }


def classify(rgb_tuple):
    
    manhattan = lambda x,y : abs(x[0] - y[0]) + abs(x[1] - y[1]) + abs(x[2] - y[2]) 
    distances = {k: manhattan(v, rgb_tuple) for k, v in COLOURS.items()}
    color = min(distances, key=distances.get)
    return color


def color_analysis(image):
    color_counter = Counter({color: 0 for color in Counter(COLOURS)})
    for pixel_count, RGB in image.getcolors(image.width * image.height):
        if(RGB!=(0,0,0)):
            color_name = classify(RGB)
            color_counter[color_name] += pixel_count


    for color in color_counter:
        pixel_count = image.width * image.height
        color_counter[color] = color_counter[color] / pixel_count


    colour = max(color_counter, key=color_counter.get)

    return colour

img_dir = "/Users/varsha/Desktop/Capstone project/segmented_2"
data_path = os.path.join(img_dir,'*g') 
files = glob.glob(data_path) 
  
colour=[]
for i in range(47,94):
    for f1 in files:
        tmp=f1.split("/")
        a=tmp[-1].split("s")
        b=a[1].split(".")
        n=b[0]
        if(i==int(n)):
            img = Image.open(f1).convert('RGB')
            col=color_analysis(img)
            colour.append(col)
            
df['colour']=colour
print(df.head())

with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(df)

df.colour.unique() 

df.to_csv (r'/Users/varsha/Desktop/Capstone project/2.csv', index = False, header=True)

   ID  Tinea captisis  Alopecia areata  Melanoma  Healthy scalp      Img
0  48               0                1         0              0  48.jpeg
1  49               0                1         0              0  49.jpeg
2  50               0                1         0              0  50.jpeg
3  51               0                1         0              0  51.jpeg
4  52               0                1         0              0  52.jpeg
   ID  Tinea captisis  Alopecia areata  Melanoma  Healthy scalp      Img  \
0  48               0                1         0              0  48.jpeg   
1  49               0                1         0              0  49.jpeg   
2  50               0                1         0              0  50.jpeg   
3  51               0                1         0              0  51.jpeg   
4  52               0                1         0              0  52.jpeg   

   colour  
0   peach  
1  yellow  
2   peach  
3   peach  
4     red  
    ID  Tinea captisis  Alopecia 

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
csv_file='/Users/varsha/Desktop/orig2.csv'
data = pd.read_csv(csv_file)

In [228]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, mean_squared_error, accuracy_score

data = {'SVC':89, 'Logistic Regression':78, 'K-NN':89} 
courses = list(data.keys()) 
values = list(data.values()) 
   
fig = plt.figure(figsize = (6, 3)) 
  
# creating the bar plot 
plt.bar(courses, values, color=['blue', 'orange', 'green'] ,
        width = 0.3) 
  
plt.xlabel("Classifier") 
plt.ylabel("Accuracy (%)") 
plt.title("Heart Disease detection - Average Accuracy achieved in 100 executions ") 
plt.show() 



NameError: name 'plt' is not defined